
dist: xenial
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install beautifulsoup4>=4.4.0 coverage==3.7.1 coveralls

script:
  - coverage run tests.py

after_success:
  - coveralls
